### PR TITLE
fix app crash issue on invalid GitHub URL input in rate screen

### LINKED ISSUE #48: [BUG] App Crash on Invalid GitHub URL Input
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Description

App crashes when an invalid GitHub URL is entered in rating screen. 

### Steps to Reproduce

1.go to rating screen.
2. enter this url "https://github.com/" and submit.  

### Screenshots

Screenshot 2023-12-27 221051

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

_No response_

### PR DESCRIPTION
**Pull request by Nithishvb**
closes #48

This PR Fixes app crash when providing an invalid GitHub URL. Improved input validation to enhance user experience.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
I don't think this is still an issue? It was fixed on the backend in this commit https://github.com/EddieHubCommunity/RepoRater/commit/bfb2fc807bf1393c747bed268816baac06afc0fa

**Comment by eddiejaoude** [comment]
Seems like it is no longer a bug, I tested with your issue url...

Screenshot 2023-12-28 at 08 33 41

**Comment by eddiejaoude** [comment]
I tested it again and it does break. I wonder if we make it easier for the user by have 2 required fields: `owner` and `name` - then we can prepend `https://github.com/`

**Comment by Nithishvb** [comment]
Hi @eddiejaoude thank you for the update. I have made a change to the code so that it may validate the github URL even if it has a slash in it. If the url does not contain the owner and repo name, it will simply throw an error.

**Comment by eddiejaoude** [comment]
ok thank you, I will test tomorrow and merge 👍

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
