### PR TITLE
fix: Color contrast issue

### LINKED ISSUE #120: [a11y]: Background and foreground colors are not screen-reader friendly
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Description

I ran an accessibility test using [Accessibility Insights](https://accessibilityinsights.io/) and it came up with the following results:

  Element has insufficient color contrast of 2.39 (foreground color: #4b5563, background color: #0f1623, font size: 9.0pt (12px), font weight: normal). Expected contrast ratio of 4.5:1

### Steps to Reproduce

N/A

### Screenshots

accessibility issue
The red icons is where the color contrasts issue occurs. 

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I plan on using the following advice from the test:
Use foreground color: #74859b and the original background color: #0f1623 to meet a contrast ratio of 4.81:1.
However, I will test the colors in a color analyzer app to ensure that these colors are accessible.

### PR DESCRIPTION
**Pull request by itsharshitrwt**
This issue fixes the problems related to background and foreground color visibility.

Fixes #120

## Screenshots

Screenshot 2024-01-27 130203

Color - Analyzer tests:-
(For white color)

Screenshot 2024-01-29 135624

(For Green color)

Screenshot 2024-01-29 135549

## Summary by CodeRabbit

- **Style**
	- Updated text colors and class names in the activity component for improved visibility and aesthetics.

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @itsharshitrwt. I highly recommend reading [coderabbit’s feedback on your contribution](https://github.com/EddieHubCommunity/RepoRater/pull/125#issuecomment-1913172242).

**Review by Abiji-2020 — COMMENTED** [review]
Have changed the colour white to gray-600 and gray to green in text-sm   

> I personally think it will be better if the colours are mentioned in hex values which will be better in many aspects

**Comment by itsharshitrwt** [comment]
Hi @Abiji-2020  , Thank you for your valuable feedback , but I'm  quiet confused . Can you please elaborate it more  like via a screenshot? 
Thanks

**Comment by Abiji-2020** [comment]
> Hi @Abiji-2020 , Thank you for your valuable feedback , but I'm quiet confused because Eddie said not to apply custom colors. Can you please elaborate it more like via screenshot? Thanks

image
This was the changes made by you, and the preferred colour changes in the issue is being made as 
image
image
 by providing the hex values of the colours for foreground and background. So in my personal opinion it is better if the colours are given in the hex value

**Comment by CBID2** [comment]
> > Hi @Abiji-2020 , Thank you for your valuable feedback , but I'm quiet confused because Eddie said not to apply custom colors. Can you please elaborate it more like via screenshot? Thanks.
> 
> image
> 
> This was the changes made by you, and the preferred colour changes in the issue is being made as image .
> 
> image .
> 
> by providing the hex values of the colours for foreground and background. So in my personal opinion it is better if the colours are given in the hex value

Hi @Abiji-2020. When it comes to displaying code, it's best to do them as snippets like this:
```
<img src="url">
```
It'll make it easier for people to understand your points

**Comment by Abiji-2020** [comment]
> > > Hi @Abiji-2020 , Thank you for your valuable feedback , but I'm quiet confused because Eddie said not to apply custom colors. Can you please elaborate it more like via screenshot? Thanks.
> > 
> > 
> > image
> > This was the changes made by you, and the preferred colour changes in the issue is being made as image .
> > image .
> > by providing the hex values of the colours for foreground and background. So in my personal opinion it is better if the colours are given in the hex value
> 
> Hi @Abiji-2020. When it comes to displaying code, it's best to do them as snippets like this:
> 
> ```
> 
> ```
> 
> It'll make it easier for people to understand your points

Thankyou @CBID2 hereafter I try to follow those

**Comment by itsharshitrwt** [comment]
Hi @Abiji-2020  ,  the screenshots provided are not visible to me .

 Screenshot 2024-02-01 111541

**Comment by eddiejaoude** [comment]
Using tailwind colours is great 👍  There should be enough options without needing to create new colours as suggested by CodeRabbit

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by CBID2** [comment]
Yay you made your first open source contribution @itsharshitrwt! 😊

**Comment by itsharshitrwt** [comment]
Thankyou so much Everyone for helping me .😊

**Comment by CBID2** [comment]
> Thankyou so much Everyone for helping me 😊 specially @CBID2 .
> 
> 

Yup! :) I highly recommend using [this website](https://opensauced.pizza/) to post about contribution. 
Also, now that you've made your first contribution, I highly recommend checking out [pizza-verse](https://github.com/open-sauced/pizza-verse). It's one of OpenSauced's many repos that you can contribute to, and it focuses on pizza :)

**Comment by itsharshitrwt** [comment]
Hi Folks , I checked the reporater's website , When i opened the website first time everything looks fine but when i opened it second time i see the green color is added to links and also white color was not visible to the time element . I'm just  concerned about it now.😔 Even though the first time i opened it everything was as expected.
  

Screenshot: 

Screenshot 2024-02-01 141208

**Comment by itsharshitrwt** [comment]
> > Thankyou so much Everyone for helping me 😊 specially @CBID2 .
> 
> Yup! :) I highly recommend using [this website](https://opensauced.pizza/) to post about contribution. Also, now that you've made your first contribution, I highly recommend checking out [pizza-verse](https://github.com/open-sauced/pizza-verse). It's one of OpenSauced's many repos that you can contribute to, and it focuses on pizza :)

Thanks @CBID2  , I will surely checkout the website.

**Comment by eddiejaoude** [comment]
> Hi Folks , I checked the reporater's website , When i opened the website first time everything looks fine but when i opened it second time i see the green color is added to links and not to the "Rated " element and also white color was not visible to the time element . I'm just concerned about it now.😔 Even though the first time i opened it everything went as expected.
> 
> Screenshot:
> 
> Screenshot 2024-02-01 141208

I moved the colours around after merging your PR, you can check the commit history - I thought the repo url will be better to be more highlighted instead

**Comment by itsharshitrwt** [comment]
> > Hi Folks , I checked the reporater's website , When i opened the website first time everything looks fine but when i opened it second time i see the green color is added to links and not to the "Rated " element and also white color was not visible to the time element . I'm just concerned about it now.😔 Even though the first time i opened it everything went as expected.
> 
> I moved the colours around after merging your PR, you can check the commit history - I thought the repo url will be better to be more highlighted instead

Thanks Eddie for clarifying this , I got worried that I made some mistakes  😅.

**Pull request merged**
